### ISSUE TITLE
iOS App Store Submit Problem

### ISSUE THREAD

**Issue by arietrouw** [BaseflowIT/flutter-permission-handler#146] opened 2019-09-05 21:02 UTC
## 🐛 Bug Report

Problems when submitting to App Store - getting rejected for lack of Descriptions for *many* permissions that I am not using.

### Expected behavior

Permissions that are not requested should not trigger the need for Purpose Strings

### Reproduction steps

Submit App to App Store that only Needs Location Permissions and has the Strings for them in the plist and none other.

### Configuration

**Version:** 3.2.2

**Platform:** 
- [x ] :iphone: iOS
- [ ] :robot: Android

**Comment by cremor** [comment] 2019-09-06 05:38
Duplicate of #26

**Closed** 2019-09-06 08:53 UTC
