### ISSUE TITLE
Strange Behavior on Flutter 0.7.3

### ISSUE THREAD

**Issue by penjual** [BaseflowIT/flutter-permission-handler#23] opened 2018-09-07 07:08 UTC
## 🐛 Bug Report

[VERBOSE-2:shell.cc(181)] Dart Error: Unhandled exception:
PlatformException(ERROR_ALREADY_REQUESTING_PERMISSIONS, A request for permissions is already running, please wait for it to finish before doing another request (note that you can request multiple permissions at the same time)., null)

### Reproduction steps
    List<PermissionGroup> permissionGroup = [
      PermissionGroup.location,
      PermissionGroup.camera,
      // PermissionGroup.storage,
    ];
    if (Theme.of(context).platform == TargetPlatform.android)
      permissionGroup.add(PermissionGroup.storage);

    List<String> ungranted = [];
    Map<PermissionGroup, PermissionStatus> permissionList =
        await permissionHandler.requestPermissions(permissionGroup);
    permissionList.forEach((a, b) {
      if (b != PermissionStatus.granted) {
        if (a != PermissionGroup.locationAlways &&
            a != PermissionGroup.locationWhenInUse)
          ungranted.add(
              a.toString().replaceAll('PermissionGroup.', '- ').toUpperCase());
      }
    });

    return ungranted;

### Configuration

**Version:** 2.0.0

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment] 2018-09-07 09:01
Hi @penjual, thank you for contacting us. 

Unfortunately I am not able to reproduce this error. I do see however that you are using an instance of the `permissionHandler` that is defined outside of the code snippet. This makes it a bit hard for me to triage what is exactly happening. However I suspect that the code snippet is ran multiple times (at least two) and the previous calls are not yet finished.

In other words (as the error message also tries to explain), you cannot run multiple requests on the same instance of the `PermissionHandler` at the same time (you will always have to wait for the first call to finish before executing a second call).

Just for your information, here is what I did to try and reproduce your issue:

- Cloned the latest version of the `PermissionHandler`;
- Pasted your code (minus the return statement) into the `void requestPermission(PermissionGroup permission) async { ... }` method of the example App (in the file `example/lib/main.dart`);
- Run the example App and tap on one of the items in the list.

I am running on the following environment:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.8.0, on Mac OS X 10.13.6 17G65, locale en-NL)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.1)
[✓] VS Code (version 1.26.1)
[✓] Connected devices (2 available)
```
And tested on a simulated iPhone 6 (iOS: 9.3)

For now I will close this issue, if you have more questions or information please feel free to reply to this issue and we will re-open it if necessary.

**Closed by mvanbeusekom** 2018-09-07 09:01 UTC

**Comment by ened** [comment] 2019-05-16 14:02
Can reproduce the issue using the sample App.

Use two fingers to request multiple permissions at the same time. The `result.error` call is not followed by a return call. PR inbound.
